FROM jenkins:lts-jdk17

USER root

RUN INSTALL_PKGS="sudo",
    apt-get update -y && \
    apt-get install -y $INSTALL_PKGS && \
    apt-get clean && \
    rm -rf /var/lib/lists/*

COPY plugin.txt /usr/share/jenkins/ref/

COPY init.groovy.d/* /usr/share/jenkins/ref/init.groovy.d/executors.groovy

EXPOSE 8080